### ISSUE TITLE
[PD] Using critical thinking to remain inclusive as a developer #31

### ISSUE THREAD

**Issue by FridayOjie** [CodeYourFuture/Table-of-Contents#5]
Coursework content
[Apply Magic Sauce](https://applymagicsauce.com/demo?authuser=0) is an alternative machine interpretation of one’s personality based on the analysis of how a person writes a sentence in an email or the types of content they like on social media. This is great when it gets the personality traits 99% accurate. But what if it goes horribly wrong and ruins lives? Choose one thing that Apply Magic Sauce can do that you don't like (or like the least). Describe what it is and say why you don't like it in 250 words. Below are three scenarios for you to contemplate:

What if the software wrongfully judges and jeopardises a person’s career without their knowledge?
Are humans unable to think for themselves and do they have to rely on machines to form a non-holistic opinion?
Are civilians expected to be on guard at all times and be careful of what they say and how they comment a post or tweet in a censored cyber world where everything is traceable and nothing is ever really erased?
Estimated time in hours
1.5

What is the purpose of this assignment?
This assignment encourages you to critically think about machine interpretation and its potential implications.

How to submit
Share the link to your Google doc on your ticket on your coursework board.

**Comment by kfklein15** [comment]
Hey! HTML CSS PD homework is still being reviewed. Please use the Fundamentals board for now :) Thank you.
